from flask import request
from ..serializers.emotionAnalyzerDto import EmotionAnalyzerDto
from ..services.emotionAnalyzer.emotionAnalyzer import EmotionAnalyzer
from flask_login import login_required
from flask_restx import Resource

api = EmotionAnalyzerDto.api
paginatedEmotionAnalyzer = EmotionAnalyzerDto.paginatedEmotionAnalyzer
emotionAnalyzer = EmotionAnalyzerDto.emotionAnalyzer
tweetAndEmotion = EmotionAnalyzerDto.tweetAndEmotion


@api.route("")
class EmotionAnalyzerController(Resource):
    @login_required
    @api.marshal_with(paginatedEmotionAnalyzer)
    @api.doc(params={'page': 'Page number', 'per_page': 'Tweets per page', 'topicTitle': 'Topic Title'})
    def get(self):
        """
        Returns a page of tweet with emotions
        """
        page = request.args.get('page', 1, type=int)
        per_page = request.args.get('per_page', 10, type=int)
        topicTitle = request.args.get('topicTitle', "", type=str)
        sa = EmotionAnalyzer()
        return sa.getEmotions(page=page, per_page=per_page, topicTitle=topicTitle)

    @login_required
    @api.expect(emotionAnalyzer)
    def post(self):
        """
        Analyses the emotion of tweets generated by a similarity algorithm.
        If some field isn't defined, analyses the emotion of a tweet topic.
        """
        reportId = request.json['reportId']
        topicTitle = request.json['topicTitle']
        algorithm = request.json['algorithm']
        threshold = request.json['threshold']
        sa = EmotionAnalyzer()
        if(not reportId or not algorithm or not threshold):
            sa.analyzeEmotionsUnfiltered(topicTitle=topicTitle)
        else:
            sa.analyzeEmotions(topicTitle=topicTitle, reportId=reportId,
                                algorithm=algorithm, threshold=threshold)


@api.route("/download")
class EmotionsDownloadController(Resource):
    @login_required
    @api.marshal_with(tweetAndEmotion)
    @api.doc(params={'topicTitle': 'Topic Title'})
    def get(self):
        """
        Returns all the tweets and emotions belonging to a topic
        """
        topicTitle = request.args.get('topicTitle', "", type=str)
        sa = EmotionAnalyzer()
        return sa.getEmotionsToDownload(topicTitle=topicTitle)
